### ISSUE TITLE
Where should the outputs be?

### ISSUE THREAD

**Issue by Xiaofei-git** [wckdouglas/fastq-tools#1]
Dear, I am trying to use splitFastq to split the fastq file, but after running the command, I don't see any output in the folder. Where the test_split should be? Thanks a lot!

$ splitFastq -i test.fq -n 4 -o test_split
From test.fq....
Splitting 4 records per file
Splitting: test_split
written test_split/01-test_split.fastq
written test_split/02-test_split.fastq
written test_split/03-test_split.fastq
written test_split/04-test_split.fastq

**Comment by wckdouglas** [comment]
@Xiaofei-git, this is an unintentional artifacts, but if you make a directory named as ```test_split/```, and run the command again, the resultant files will be written there correctly.
